name: something
description: something
title: something
labels: "something"
body:
  - type: textarea
    id: something
    attributes:
      label: provide email and ip
      description: |
        examples:
          - email: yourEmail@domain.org
      value: |
        - ip:
      render: markdown
