name: Test Action
description: something
title: something
labels: "something"
body:
  - type: textarea
    id: something
    attributes:
      label: Provide email and ip just as described in template
      description: |
        examples:
          email: yourEmail@domain.org
          ip: 0.0.0.0
      value: |
        email:
        ip:
      render: markdown
