name: IP whitelisting action
description: action enables updating of ip whitelisting list
title: Whitelist IP
labels: "whitelist ip"
body:
  - type: textarea
    id: something
    attributes: 
      description: |
        examples:
          - email: yourEmail@domain.org
      value: |
        - ip:
      render: markdown
